" ~/.vimrc

" ------------ Vundle setup ------------

set nocompatible
filetype off

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'chriskempson/base16-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'

" Plugins must be added before the following line
call vundle#end()
filetype plugin indent on

" ----------- General config -----------

set number                              " Display line numbers
set noshowmode                          " Remove default mode indicator

" ----------- Theme settings -----------

syntax on
set background=dark
colorscheme base16-ocean
set term=screen-16color
set t_Co=16

" -------------- Nerdtree --------------

" Open NERDTree automatically when vim starts up and focus on main window
autocmd VimEnter * NERDTree | wincmd p

" Close NERDTree if it's the only window left open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Disable the 'Bookmarks' label and 'Press ? for help' text
let NERDTreeMinimalUI=1

" -------------- Airline ---------------

let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#fnamemod=':t'
let g:airline_powerline_fonts=1
set laststatus=2

" --------------- Ctrl-P ---------------

" Ignore the following file extensions and directories
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
let g:ctrlp_custom_ignore = '\v[\/](bower_components|dist|node_modules)|(\.(git))$'

" ------------ Key bindings ------------

inoremap jj <Esc>
