" ~/.vimrc

" ------------ Vundle setup ------------

set nocompatible
filetype off

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/syntastic'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'ervandew/supertab'
Plugin 'bling/vim-airline'
Plugin 'pangloss/vim-javascript'
Plugin 'tpope/vim-repeat'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'chriskempson/base16-vim'
Plugin 'editorconfig/editorconfig-vim'

" Plugins must be added before the following line
call vundle#end()
filetype plugin indent on

" ----------- General config -----------

set number                              " Display line numbers
set backspace=indent,eol,start          " Allow backspace in insert mode
set noshowmode                          " Remove default mode indicator
set cursorline                          " Highlight current line
set wildmenu                            " Display visual autocomplete for the command menu
set incsearch                           " Search as characters are entered
set hlsearch                            " Highlight search matches
set scrolloff=10                        " Keep more lines on-screen when scrolling up/down

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

set undolevels=1000                     " Use many muchos levels of undo

" ----------- Theme settings -----------

syntax on
colorscheme base16-ocean
set background=dark
set term=screen-16color
set t_Co=16

" ------------- Indentation ------------

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

set list listchars=tab:>.,trail:.,extends:#,nbsp:.

" --------- Turn off swap files --------

set noswapfile
set nobackup
set nowb

" -------------- Nerdtree --------------

" Disable the 'Bookmarks' label and 'Press ? for help' text
let NERDTreeMinimalUI=1

" -------------- Airline ---------------

let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#fnamemod=':t'
let g:airline_powerline_fonts=1
set laststatus=2

" --------------- Ctrl-P ---------------

" Ignore the following file extensions and directories
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
let g:ctrlp_custom_ignore = '\v[\/](bower_components|dist|node_modules)|(\.(git))$'

" ------------ Key bindings ------------

inoremap jj <Esc>

" Easier window navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Turn off search highlights
nnoremap <silent> <Space> :nohlsearch<cr><ESC>
