# ~/.bash_profile

# Set ls Environment variables
# http://ss64.com/osx/ls-env.html
export CLICOLOR='Yes'
export LSCOLORS='exfxcxdxbxegedabagacad'

# Append to the history file, don't overwrite it
shopt -s histappend

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

declare -a files=(
    "$HOME/.aliases"
    "$HOME/.bash_prompt"
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [ -r ${files[$index]} ]; then
        source ${files[$index]}
    fi
done

unset files

# Add rbenv to $PATH
export PATH="$HOME/.rbenv/bin:$PATH"

# Add rbenv init to shell
eval "$(rbenv init -)"

# Add postgres.app to $PATH
export PATH="/Applications/Postgres93.app/Contents/MacOS/bin:$PATH"
