# ~/.bash_profile

# Set ls Environment variables
# http://ss64.com/osx/ls-env.html
export CLICOLOR='Yes'
export LSCOLORS='exfxcxdxbxegedabagacad'

# Append to the history file, don't overwrite it
shopt -s histappend

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

declare -a files=(
    "$HOME/.aliases"
    "$HOME/.bash_prompt"
    "$HOME/.git-completion.bash"
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [ -r ${files[$index]} ]; then
        source ${files[$index]}
    fi
done

unset files

# Virtualenvwrapper settings
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
source /usr/local/bin/virtualenvwrapper.sh
