# ~/.bash_profile

# Append to the history file, don't overwrite it
shopt -s histappend

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

declare -a files=(
    "$HOME/.aliases"
    "$HOME/.bash_prompt"
    "$HOME/.rvm/scripts/rvm"
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [ -r ${files[$index]} ]; then
        source ${files[$index]}
    fi
done

unset files

# Node package manager
export PATH="/usr/local/share/npm/bin:$PATH"

# Some rbenv magic
if which rbenv > /dev/null; then
    eval "$(rbenv init -)";
fi

# Virtual envs ?
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Sites
source /usr/local/bin/virtualenvwrapper.sh

# Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
